[project]
name = "rlbook"
version = "0.1.0"
description = "Practical Reinforcement Learning: From Algorithms to Applications"
authors = [
    {name = "Pierre-Luc Bacon"}
]
requires-python = ">=3.12"
dependencies = [
    "altair==6.2.2",
    "casadi",
    "cvxpy",
    "do-mpc",
    "ecos>=2.0.14",
    "ipykernel",
    "ipywidgets",
    "jax",
    "jaxlib",
    "jupyter-book==2.1.6",
    "jupyter-book-marimo==0.0.3",
    "jupyterlite-core==0.8.1",
    "jupyterlite-xeus==5.0.0",
    "matplotlib",
    "nbclient",
    "nbformat",
    "numpy",
    "openap",
    "openap-top",
    "optax",
    "pandas",
    "pyenergyplus-lbnl",
    "pyomo",
    "scikit-learn",
    "scipy",
    "swing-rl[jax] @ git+https://github.com/pierrelux/swing-rl.git@d579663fc81c044729f4d3ab60bf63bcdbd27b9a",
    "vl-convert-python",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []

[dependency-groups]
artifacts = ["pybamm==26.6.2.0"]
dev = ["pytest>=8.0"]
