#!/usr/bin/env python3
"""Build committed BIXI controller evidence and chapter visuals.

This is an explicit maintenance command. A normal MyST build reads the JSON,
CSV, SVG, and PDF outputs and never reruns the Monte Carlo experiment.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict
import csv
import json
from pathlib import Path
import platform
import sys
from typing import Any

import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
CODE = ROOT / "code"
sys.path.insert(0, str(CODE))

from bixi_control import (  # noqa: E402
    load_completed_profile,
    load_event_trace,
    load_scenario,
    make_censoring_counterexample,
    make_controller,
    make_open_loop_controller,
    sample_poisson_trace,
    sha256,
    simulate,
    simulate_fluid,
)
from bixi_replay import (  # noqa: E402
    make_censoring_figure,
    make_feedback_evidence_figure,
    make_model_interface_figure,
    save_figure_pair,
)


DATA = ROOT / "data" / "bixi"
ARTIFACTS = ROOT / "artifacts" / "bixi"
ASSETS = ROOT / "_static" / "bixi"
INPUT_FILES = (
    DATA / "manifest.json",
    DATA / "stations.json",
    DATA / "completed_event_profile.csv",
    DATA / "showcase_events.csv",
    ROOT / "code" / "bixi_control.py",
    ROOT / "code" / "bixi_replay.py",
    ROOT / "scripts" / "build_bixi_artifacts.py",
)
CONTROLLERS = ("none", "open_loop", "feedback")
METRIC_FIELDS = (
    "service_failures",
    "lost_rentals",
    "rejected_returns",
    "bikes_moved",
    "truck_distance_km",
    "terminal_imbalance",
    "objective",
)


def _verify_derived_inputs() -> dict[str, Any]:
    manifest = json.loads((DATA / "manifest.json").read_text(encoding="utf-8"))
    expected = manifest["derived_files"]
    for name, digest in expected.items():
        path = DATA / name
        if not path.is_file() or sha256(path) != digest:
            raise ValueError(f"derived BIXI input is missing or stale: {name}")
    return manifest


def _summary(values: list[float]) -> dict[str, float]:
    array = np.asarray(values, dtype=float)
    return {
        "mean": float(np.mean(array)),
        "q10": float(np.quantile(array, 0.10)),
        "median": float(np.quantile(array, 0.50)),
        "q90": float(np.quantile(array, 0.90)),
    }


def _jsonable(value: Any) -> Any:
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    return value


def _write_results_fragment(path: Path, artifact: dict[str, Any]) -> None:
    scenarios = artifact["monte_carlo"]["scenarios"]
    nominal = scenarios["nominal"]["controllers"]
    pulse = scenarios["paired_pulse"]["controllers"]
    labels = {
        "none": "No relocation",
        "open_loop": "Frozen open loop",
        "feedback": "Inventory feedback",
    }
    lines = [
        "<!-- Generated by scripts/build_bixi_artifacts.py; do not edit by hand. -->",
        "",
        "| controller | mean failures, rate model | mean failures, paired pulse |",
        "|---|---:|---:|",
    ]
    for name in CONTROLLERS:
        lines.append(
            f"| {labels[name]} | {nominal[name]['service_failures']['mean']:.2f} "
            f"| {pulse[name]['service_failures']['mean']:.2f} |"
        )
    lines.extend(
        [
            "",
            (
                "On the nominal traces, feedback lowers mean failures from "
                f"{nominal['open_loop']['service_failures']['mean']:.2f} to "
                f"{nominal['feedback']['service_failures']['mean']:.2f} relative "
                "to the frozen plan. The frozen plan moves a median "
                f"{nominal['open_loop']['bikes_moved']['median']:.0f} bicycles over "
                f"{nominal['open_loop']['truck_distance_km']['median']:.2f} km. "
                "Feedback moves a median "
                f"{nominal['feedback']['bikes_moved']['median']:.0f} bicycles over "
                f"{nominal['feedback']['truck_distance_km']['median']:.2f} km under "
                "the rate model and "
                f"{pulse['feedback']['bikes_moved']['median']:.0f} bicycles over "
                f"{pulse['feedback']['truck_distance_km']['median']:.2f} km under "
                "the paired pulse. "
                "The service gain therefore comes with a visible relocation cost."
            ),
            "",
            (
                "Values are means over 512 common-random-number event traces. "
                "They describe the teaching simulator calibrated from completed "
                "trips, not measured failures in BIXI operations."
            ),
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def build(*, seeds: int = 512) -> dict[str, Any]:
    if seeds <= 0:
        raise ValueError("seeds must be positive")
    data_manifest = _verify_derived_inputs()
    scenario = load_scenario(DATA / "stations.json")
    profile = load_completed_profile(DATA / "completed_event_profile.csv", scenario)
    showcase_trace = load_event_trace(DATA / "showcase_events.csv", scenario)
    open_loop = make_open_loop_controller(scenario, profile)

    open_loop_plan: list[dict[str, Any]] = []
    location = scenario.initial_truck_station
    for decision, action in enumerate(open_loop.actions):
        open_loop_plan.append(
            {
                "decision_index": decision,
                "local_time": f"{7 + decision // 4:02d}:{15 * (decision % 4):02d}",
                "origin": int(location),
                "transfer": int(action.transfer),
                "destination": int(action.destination),
            }
        )
        location = action.destination

    fluid = simulate_fluid(scenario, profile, open_loop)
    showcase_runs = {
        name: simulate(
            scenario,
            showcase_trace,
            make_controller(name, scenario, profile),
        ).to_dict()
        for name in CONTROLLERS
    }

    rows: list[dict[str, Any]] = []
    inventory_by_scenario: dict[str, dict[str, list[np.ndarray]]] = {}
    for scenario_name, paired_pulse in (("nominal", False), ("paired_pulse", True)):
        inventory_by_scenario[scenario_name] = {name: [] for name in CONTROLLERS}
        for seed in range(seeds):
            trace = sample_poisson_trace(
                scenario,
                profile,
                seed,
                paired_pulse=paired_pulse,
            )
            for name in CONTROLLERS:
                result = simulate(
                    scenario,
                    trace,
                    make_controller(name, scenario, profile),
                )
                rows.append(
                    {
                        "scenario": scenario_name,
                        "seed": seed,
                        "controller": name,
                        **asdict(result.metrics),
                    }
                )
                inventory_by_scenario[scenario_name][name].append(
                    result.station_inventory
                )

    scenarios: dict[str, Any] = {}
    for scenario_name in ("nominal", "paired_pulse"):
        scenario_rows = [row for row in rows if row["scenario"] == scenario_name]
        controllers: dict[str, Any] = {}
        for name in CONTROLLERS:
            controller_rows = [row for row in scenario_rows if row["controller"] == name]
            stacked = np.stack(inventory_by_scenario[scenario_name][name])
            controllers[name] = {
                field: _summary([float(row[field]) for row in controller_rows])
                for field in METRIC_FIELDS
            }
            controllers[name]["inventory_envelope"] = {
                "q10": np.quantile(stacked, .10, axis=0).tolist(),
                "median": np.quantile(stacked, .50, axis=0).tolist(),
                "q90": np.quantile(stacked, .90, axis=0).tolist(),
            }
        by_key = {
            (int(row["seed"]), str(row["controller"])): row for row in scenario_rows
        }
        differences = np.asarray(
            [
                by_key[(seed, "open_loop")]["service_failures"]
                - by_key[(seed, "feedback")]["service_failures"]
                for seed in range(seeds)
            ],
            dtype=float,
        )
        scenarios[scenario_name] = {
            "controllers": controllers,
            "paired_open_loop_minus_feedback_failures": {
                **_summary(differences.tolist()),
                "feedback_wins_fraction": float(np.mean(differences > 0)),
                "tie_fraction": float(np.mean(differences == 0)),
                "feedback_loses_fraction": float(np.mean(differences < 0)),
            },
        }

    artifact: dict[str, Any] = {
        "schema_version": 1,
        "metadata": {
            "input_files": {
                str(path.relative_to(ROOT)): sha256(path) for path in INPUT_FILES
            },
            "official_trip_archive_sha256": data_manifest["sources"]["trip_archive"]["sha256"],
            "official_station_snapshot_sha256": data_manifest["sources"]["station_information"]["sha256"],
            "license": data_manifest["license"],
            "attribution": data_manifest["attribution"],
            "python_version": platform.python_version(),
            "numpy_version": np.__version__,
            "random_generator": "numpy.random.Generator(PCG64)",
            "showcase_is_selected": True,
        },
        "scenario": {
            "stations": [
                {
                    "name": station.name,
                    "station_id": station.station_id,
                    "short_name": station.short_name,
                    "lat": station.latitude,
                    "lon": station.longitude,
                    "capacity": station.capacity,
                }
                for station in scenario.stations
            ],
            "initial_inventory": scenario.initial_inventory.tolist(),
            "horizon_start_local": scenario.horizon_start_local,
            "horizon_minutes": scenario.horizon_minutes,
            "control_period_minutes": scenario.control_period_minutes,
            "truck_capacity": scenario.truck_capacity,
            "transfer_limit": scenario.transfer_limit,
            "initial_truck_station": scenario.initial_truck_station,
            "distance_km": scenario.distance_km.tolist(),
            "objective": {
                "expression": "failures + 0.05 moved bikes + 0.2 distance_km + 0.1 terminal imbalance",
                "service_failure": scenario.failure_weight,
                "bike_moved": scenario.bike_moved_weight,
                "truck_distance_km": scenario.distance_weight,
                "terminal_imbalance": scenario.terminal_imbalance_weight,
            },
        },
        "profile": {
            "training_day_count": profile.training_day_count,
            "bin_start_minutes": profile.bin_start_minutes.tolist(),
            "mean_completed_starts": profile.completed_starts.tolist(),
            "mean_completed_ends": profile.completed_ends.tolist(),
            "semantics": "Empirical means of completed starts and ends; not attempted demand.",
        },
        "open_loop_plan": open_loop_plan,
        "deterministic_mean_flow": {
            "checkpoint_time_minutes": fluid.checkpoint_time_minutes.tolist(),
            "station_inventory": fluid.station_inventory.tolist(),
            "cumulative_lost_rentals": fluid.cumulative_lost_rentals.tolist(),
            "cumulative_rejected_returns": fluid.cumulative_rejected_returns.tolist(),
        },
        "showcase": {
            "date": data_manifest["derivation"]["showcase_date"],
            "selection_note": data_manifest["derivation"]["showcase_selection"],
            "event_semantics": data_manifest["derivation"]["event_semantics"],
            "completed_counts": data_manifest["showcase_completed_counts"],
            "controllers": showcase_runs,
        },
        "monte_carlo": {
            "seed_start": 0,
            "seed_stop_exclusive": seeds,
            "common_random_numbers": True,
            "model": "Independent Poisson completed starts/ends by station and 15-minute bin; event times uniform within bin.",
            "paired_pulse": {
                "semantics": "Eight independent extra rental attempts at Prince-Arthur at 07:47 and eight independent extra return attempts at Aylmer at 07:57.",
                "feedback_first_observes_resulting_inventory_at": "08:00",
            },
            "scenarios": scenarios,
        },
        "censoring_counterexample": make_censoring_counterexample(),
        "limitations": [
            "The source reports completed trips, not attempted demand or service failures.",
            "The source does not label operator relocation.",
            "Capacities and coordinates come from the 2 September 2026 GBFS snapshot and may differ from July 2024 hardware.",
            "Independent Poisson events omit spatial correlation, weather, holidays, and substitution among stations.",
            "The showcase morning was chosen for legibility and is not unbiased evidence.",
            "The heuristic feedback controller is illustrative, not a reconstruction of BIXI operations.",
        ],
    }
    artifact = _jsonable(artifact)
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    ASSETS.mkdir(parents=True, exist_ok=True)
    artifact_path = ARTIFACTS / "textbook_results.json"
    artifact_path.write_text(
        json.dumps(artifact, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )

    fieldnames = ["scenario", "seed", "controller"] + list(asdict(simulate(
        scenario, showcase_trace, make_controller("none", scenario, profile)
    ).metrics))
    metrics_path = ARTIFACTS / "controller_metrics.csv"
    with metrics_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)

    results_path = ARTIFACTS / "results.md"
    _write_results_fragment(results_path, artifact)

    figures = (
        (make_model_interface_figure(artifact), ASSETS / "bixi-model-interface"),
        (make_feedback_evidence_figure(artifact), ASSETS / "bixi-feedback-evidence"),
        (make_censoring_figure(artifact), ASSETS / "bixi-completed-trip-censoring"),
    )
    for figure, stem in figures:
        save_figure_pair(figure, stem)
        plt.close(figure)

    outputs = [artifact_path, metrics_path, results_path]
    outputs.extend(sorted(ASSETS.glob("bixi-*.*")))
    artifact_manifest = {
        "schema_version": 1,
        "command": "uv run python scripts/build_bixi_artifacts.py --seeds 512",
        "inputs": {str(path.relative_to(ROOT)): sha256(path) for path in INPUT_FILES},
        "outputs": {str(path.relative_to(ROOT)): sha256(path) for path in outputs},
        "protocol": {
            "seeds": list(range(seeds)),
            "common_random_numbers": True,
            "quantiles": [0.10, 0.50, 0.90],
        },
    }
    (ARTIFACTS / "manifest.json").write_text(
        json.dumps(artifact_manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return artifact


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seeds", type=int, default=512)
    args = parser.parse_args()
    build(seeds=args.seeds)


if __name__ == "__main__":
    main()
